# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
